import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "css/Global.scss"

const font = Poppins({ 
  weight:["100","200","300","400","500","600","700","800","900"] ,
  display:"swap",
  adjustFontFallback:true,
  preload:true,
  subsets:["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={font.className}>{children}</body>
    </html>
  );
}
